server:
  port: 80

spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: my_domain_route
        uri: http://localhost:80
        predicates:
        - Host=mydomain.com

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8283/eureka/