server:
  port: 8286
  servlet:
    context-path: /conversation

spring:
  application:
    name: conversation

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/conversation
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver