CREATE TABLE `数据表` (
  `数据表下标` int unsigned NOT NULL AUTO_INCREMENT,
  `数据对象` json DEFAULT NULL,
  `时间` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`数据表下标`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;