server:
  port: 8286

spring:
  application:
    name: demo-config
  cloud:
    config:
      server:
        git:
          uri:

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8283/eureka/
