server:
  port: 8280
  servlet:
    context-path: /demo1

spring:
  application:
    name: demo1

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8283/eureka/

feign:
  hystrix:
    enabled: true


hystrix:
  threadpool:
    default:
      coreSize: 1 #核心线程池
      maxQueueSize: 2 #最大线程池
      maximumSize: 1
      queueSizeRejectionThreshold: 5
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 100000000