server:
  port: 8280
  servlet:
    context-path: /demo1

spring:
  application:
    name: demo1

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8283/eureka/

feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000